FROM node:18-slim as builder

RUN mkdir /app

WORKDIR /app

COPY package*.json ./

RUN apt-get update && apt-get install -y npm

COPY src/client ./

RUN npm install --force

RUN npm run build


FROM nginx:1.25-alpine

COPY nginx.conf /etc/nginx/conf.d

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]