FROM python:3.10

RUN mkdir -p /app/src/server/

WORKDIR /app/src/server

COPY src/server ./

RUN apt-get update && apt-get install -y ffmpeg

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

EXPOSE 8000

WORKDIR /app

CMD ["uvicorn", "src.server.main:app", "--host", "0.0.0.0", "--port", "8000"]
