services:
  localstack:
    image: localstack/localstack:latest
    container_name: annihilator_localstack
    restart: always
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3 
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
    env_file:
      - .env
    volumes:
      - ./.localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: annihilator_backend 
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    depends_on:
      - localstack

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: annihilator_frontend 
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env
 